AWSTemplateFormatVersion: 2010-09-09

Description: This is a template to create the Servers infrastructure of T3C7 Monday Lab Week 6

Parameters:
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'

Resources:
  WebserverSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP and SSH to T3C7 Mon Web Servers
      GroupName: WebserverSecurityGroup
      VpcId: !ImportValue T3C7-Mon-VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: T3C7 Web Server Security Group

  PublicInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: !Ref LatestAmiId
      KeyName: us-west-2-key
      SubnetId: !ImportValue T3C7-Mon-Public-Subnet-1
      SecurityGroupIds:
        - !Ref  WebserverSecurityGroup
      Tags:
        - Key: Name
          Value: T3C7 Mon Public Instance
      UserData: !Base64 |
        #!/bin/bash
        yum update -y
        amazon-linux-extras install -y lamp-mariadb10.2-php7.2 php7.2
        yum install -y httpd mariadb-server
        systemctl start httpd
        systemctl enable httpd
        usermod -a -G apache ec2-user
        chown -R ec2-user:apache /var/www
        chmod 2775 /var/www
        find /var/www -type d -exec chmod 2775 {} \;
        find /var/www -type f -exec chmod 0664 {} \;
        echo "<?php phpinfo(); ?>" > /var/www/html/phpinfo.php

  PrivateInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: !Ref LatestAmiId
      KeyName: us-west-2-key
      SubnetId: !ImportValue T3C7-Mon-Private-Subnet-1
      SecurityGroupIds:
        - !Ref WebserverSecurityGroup
      Tags:
        - Key: Name
          Value: T3C7 Mon Private Instance
